### ISSUE TITLE
Blocks bug when starting a second trial

### ISSUE THREAD

**Issue by anthonyromyn** [DuncanLab/RoadRAGE#9]
Hi RoadRAGE Team,

Using the default .json, a block with three trials (trial id 7) bugs out after the first trial is completed. I posted a quick screen recording here https://vimeo.com/315544583 with password 'RoadRAGE'.

Best,
Anthony

**Comment by codyhowarth** [comment]
@anthonyromyn This is actually the intended behavior, I've just set a bad default amount for the `timeAlotted` variable in the json config. Essentially what happens is if there aren't enough prefabs specified for the time allotted, the software throws an error and scene gets messed up. Reason being is otherwise the car would simply keep driving off of the end of the last prefab. 

I've altered this behavior slightly to provide a more detailed error message, and to exit the program/stop the editor if this has occurred. If you encounter this problem simply set up some more prefabs, or decrease the time allotted.
